#!/bin/sh
set -e

if command -v systemctl >/dev/null 2>&1; then
  systemctl daemon-reload || true
  systemctl enable sni-forwarder.service || true
  systemctl restart sni-forwarder.service || true
fi

exit 0
