#!/bin/sh
set -e

if command -v systemctl >/dev/null 2>&1; then
  systemctl stop sni-forwarder.service || true
  systemctl disable sni-forwarder.service || true
  systemctl daemon-reload || true
fi

exit 0
